### PR TITLE
Fix url in setup.py

### PR DESCRIPTION
**Pull request by altaurog**
Oops.  I just noticed the url in setup.py is wrong.  Here I've fixed it.

Are you able to release to pypi?

### CODE REVIEW

**Comment by wiswaud** [comment]
i should be able to, i'll check; do you have an account there btw?

**Comment by altaurog** [comment]
I don't think so.  Haven't set one up yet.  Why?

**Comment by wiswaud** [comment]
ok - so we're not the owners of the package there. I've just sent an email to the owner asking him to give me permissions, will see what happens.

**Comment by meshy** [comment]
This project is just what I need, thanks!

Would it be possible to `push --tags` to github, please?

Looks like you're listed in the owners now on pypi, too `:)`

**Comment by altaurog** [comment]
I already pushed the tags to my repo.  Is there anything else I need to do? (I generally use hg/bitbucket, and don't have much git/github experience.)

**Comment by meshy** [comment]
Sorry, I meant to ask @wiswaud to push tags. I don't think you have permissions to tag this repo.

**Comment by altaurog** [comment]
I thought so, but just wanted to be certain.

**Pull request merged**
