### PR TITLE
Added tests and fixes

### PR DESCRIPTION
**Pull request by altaurog**
This poor project seems to be languishing.  We would like to start using it in production so I have given it a bit of attention:
- I reorganized the code
- I added tests for the current ArrayField classes
- I fixed the DateFieldArray, as well as lookups for the other fields
- I updated the documentation
- I added an AUTHORS.txt file

I also took the liberty of reformatting the docs and assigning a new version number.

I have no problem pulling from my fork on github into production environments, but it would be great to have these changes integrated back upstream and released on pypi.

### CODE REVIEW

**Comment by wiswaud** [comment]
wow - awesome work thank you!
just one thing before i pull - i see that you now let dbarray init itself on other db connections than psycopg2, but it's unclear to me from a cursory look where it's serializing / deserializing. IOW, looks like it'll just bomb later, but i'm likely just missing something?

**Comment by altaurog** [comment]
I'm not sure to what you are referring.  There is a function `require_postgres()` which is called by `db_type()` that raises an exception if the db connection is not psycopg2 or postgis.  I didn't touch that part.  I also didn't test on other db connections to see if it fails.

**Comment by wiswaud** [comment]
redhog's email address turned out to be undeliverable, so i've filed https://sourceforge.net/p/pypi/support-requests/306/ to regain ownership. Will upload new version when i can, but in the meantime, assuming you're using virtualenv, you can always include it by git url?

**Comment by altaurog** [comment]
Yes of course; we already are.

**Pull request merged**
